### ISSUE TITLE
n.!hAC is not a function error when loading a project

### ISSUE THREAD

**Issue by MeStrak** [Scirra/Construct-3-bugs#926]
## Problem description

Since upgrading to Construct 3 v62 I get the error message 'n.!hAC is not a function' when trying to open a project I'm working on at 0.1% loading. This is usually where I am prompted to install the LiteTween addon.

Rolled back to R61 and it works fine.

## Attach a .c3p

Working on a deadline and I don't have time to create a new project to try and replicate it, and I'm not updating other browsers.

The only thing unusual about the project that I can think of is that I have the LiteTween addon installed and configured to install every time.

## Steps to reproduce

1. Open project
2. Download from Google Drive completes
3. n.!hAC is not a function error shown at 0.1% of project load

## Observed result

Error message n.!hAC is not a function.

## Expected result

Project does not open.

## Affected browsers

* Chrome: yes
* Firefox: not tested
* Edge: not tested
* Safari: not tested

## System details

Platform information
Browser: Chrome
Browser version: 61.0.3163.100
Browser engine: Blink
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
C3 release: r62
Language setting: en-US

Local storage
Storage quota (approx): 30 gb
Storage usage (approx): 82 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

This browser does not support pluralisation rules. Plural forms may not be correct.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Vendor: Google Inc.
Renderer: ANGLE (AMD Mobility Radeon HD 5000 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks similar to #924

**Comment by MeStrak** [comment]
Yes sorry, I didn't check the list properly before. I don't have the other 'failed to load' messages, but the n.!hAC message is the same.
    On Thursday, 12 October 2017, 20:18:37 CEST, Ashley (Scirra) <notifications@github.com> wrote:  
 
 
Looks similar to #924

**Comment by joelmayer87** [comment]
Try empying the history and cache in Chrome and start the browser and editor again, it worked after that for me...

**Comment by armandoalonso** [comment]
i was having the same issue, followed joelmayer87 advice and clear browser cache and history and it worked after that. thanks

**Comment by shortercode** [comment]
Duplicate of #924.

Bug is the inability to open project that include a bundled addon that is already installed locally.
